name: "[helios] Issue"
description: Issues related to the Helios solar system visualization
title: "[helios] "
labels: ["project:helios"]
body:
  - type: markdown
    attributes:
      value: |
        ## Helios Solar System Issue
        Solar system visualization at **helios.too.foo**

        ### 🤖 AI Automation Available
        Enable Claude agents to automatically implement this issue.
        Talk naturally in comments, get live previews, iterate quickly!

  - type: checkboxes
    id: automation
    attributes:
      label: Automation
      description: Enable Claude AI automation?
      options:
        - label: "🤖 Enable automation (adds `claude-auto` label)"
          required: false

  - type: dropdown
    id: type
    attributes:
      label: Issue Type
      options:
        - Bug fix
        - New feature
        - UI/UX improvement
        - Performance optimization
        - Refactor
        - Documentation
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Clear description of the issue or feature
      placeholder: What needs to be done?
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: What defines "done" for this issue?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Visual tests pass
    validations:
      required: true

  - type: textarea
    id: visual
    attributes:
      label: Visual Reference
      description: Screenshots, mockups, or visual descriptions if applicable
      placeholder: Describe expected visual output or attach images

  - type: textarea
    id: technical
    attributes:
      label: Technical Notes
      description: Any relevant technical details or affected components
      placeholder: |
        Affected components:
        - Canvas rendering
        - Animation loop

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - P0 - Critical
        - P1 - High
        - P2 - Medium
        - P3 - Low
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---
        ### 💬 How Automation Works

        **With `claude-auto` label:**
        1. Planner (Opus) analyzes issue → posts plan (60s)
        2. Executor (Sonnet) implements → deploys preview
        3. You comment naturally: "make it bigger", "change approach", "ship it!"
        4. Agents respond in 5-60s (adapts to your activity)
        5. Preview: `issue-{number}-helios.too.foo`

        **Cost:** ~$0.20/issue | **Time:** 5-15 min from idea to preview
