name: "[portfolio] Issue"
description: Issues related to the portfolio/personal website
title: "[portfolio] "
labels: ["project:portfolio"]
body:
  - type: markdown
    attributes:
      value: |
        ## Portfolio Issue
        This issue affects the `portfolio` project - interactive robotics demos and personal website.

  - type: dropdown
    id: type
    attributes:
      label: Issue Type
      options:
        - Bug fix
        - New demo
        - UI/UX improvement
        - Performance optimization
        - Refactor
        - Documentation
    validations:
      required: true

  - type: dropdown
    id: demo
    attributes:
      label: Affected Demo
      options:
        - Boids
        - Pathfinding (A*)
        - EKF
        - About page
        - All demos
        - Infrastructure
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Clear description of the issue or feature
      placeholder: What needs to be done?
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: What defines "done" for this issue?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Tests pass
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - P0 - Critical
        - P1 - High
        - P2 - Medium
        - P3 - Low
    validations:
      required: true
