name: "[too.foo] Issue"
description: Issues related to the too.foo visualization project
title: "[too.foo] "
labels: ["project:too.foo"]
body:
  - type: markdown
    attributes:
      value: |
        ## too.foo Visualization Issue
        This issue affects the `too.foo` project - visualization using the core engine.

  - type: dropdown
    id: type
    attributes:
      label: Issue Type
      options:
        - Bug fix
        - New feature
        - UI/UX improvement
        - Performance optimization
        - Refactor
        - Documentation
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Clear description of the issue or feature
      placeholder: What needs to be done?
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: What defines "done" for this issue?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Tests pass
    validations:
      required: true

  - type: textarea
    id: technical
    attributes:
      label: Technical Notes
      description: Any relevant technical details or affected components

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - P0 - Critical
        - P1 - High
        - P2 - Medium
        - P3 - Low
    validations:
      required: true
